services:
  go:
    build:
        context: .
        dockerfile: ./compose/echo/Dockerfile
    ports:
        - "8080:8080"
    volumes:
        - .:/api
        - /root/.ssh/nginx/:/usr/local/nginx/conf/
    extra_hosts:
    - "host.docker.internal:host-gateway" #DNS resolves to internal ip used by host

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./compose/nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - /root/.ssh/nginx/:/usr/local/nginx/conf/
  #   network_mode: "host"
  #   depends_on:
  #     - go

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./compose/caddy/Caddyfile:/etc/caddy/Caddyfile
    network_mode: "host"
    depends_on:
      - go
  
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /root/minio/data:/data
    environment:
        MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
        MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
        MINIO_ROOT_USER: ${MINIO_ROOT_USER}
        MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        MINIO_ADDRESS: ":9000"
        MINIO_CONSOLE_ADDRESS: ":9001"
        MINIO_BROWSER_REDIRECT_URL: "https://app.alexnorgaard.dk/minio/ui/" # Redirect to the UI does not work without this
    command: server /data