services:
  go:
    build:
        context: .
        dockerfile: ./compose/echo/Dockerfile
    ports:
        - "8000:8000"
        - "5432:5432"
    volumes:
        - .:/api
        - /root/.ssh/nginx/:/usr/local/nginx/conf/
    # command: go run cmd/api/main.go

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./compose/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /root/.ssh/nginx/:/usr/local/nginx/conf/
    network_mode: "host"
    depends_on:
      - go
  
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /root/minio/data:/data
    environment:
        MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
        MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
        MINIO_ROOT_USER: ${MINIO_ROOT_USER}
        MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        MINIO_ADDRESS: ":9000"
        MINIO_CONSOLE_ADDRESS: ":9001"
        MINIO_BROWSER_REDIRECT_URL: "https://app.alexnorgaard.dk/minio/ui/"
    command: server /data

  minio-mc:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc anonymous set download event-banner-images;
      exit 0;
      "